ToDo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('allauth.urls')),

]

app/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path('', TaskListView.as_view(), name='task_list'),
    path('<int:pk>/', TaskDetailView.as_view(), name='task_detail'),
    path('create/', TaskCreateView.as_view(), name='task_create'),
    path('edit/<int:pk>/', TaskUpdateView.as_view(), name='task_edit'),
    path('complete/<int:pk>/', task_complete, name='complete'),
    path('delete/<int:pk>/', TaskDeleteView.as_view(), name='task_delete'),
    path('profile/<int:pk>/', UserUpdateView.as_view(), name='profile'),

    path('subtask/<int:pk>/', SubTaskCreateView.as_view(), name='subtask_create'),
    path('subtask/<int:pk>/update/', SubTaskUpdateView.as_view(), name='subtask_update'),
    path('subtask/<int:pk>/delete', SubTaskDeleteView.as_view(), name='subtask_delete'),
    path('subtask/<int:pk>/complete/', subtask_complete, name='subtask_complete'),

    path('complete_list/<int:pk>/', TaskCompleteListView.as_view(), name='complete_list'),
    path('tomorrow_list/<int:pk>/', TaskTomorrowListView.as_view(), name='tomorrow_list'),
    path('yesterday_list/<int:pk>/', TaskYesterdayListView.as_view(), name='yesterday_list'),
    path('today_list/<int:pk>/', TaskTodayListView.as_view(), name='today_list')
    ]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(default=0)

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

    def __str__(self):
        return f'{self.user.username}: {self.rating}'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


def slug_name(title):
    dct = {'А': 'A', 'Б': 'B', 'В': 'V', 'Г': 'G', 'Д': 'D', 'Е': 'E', 'Ё': 'YO', 'Ж': 'ZH',
           'З': 'Z', 'И': 'I', 'Й': 'Y', 'К': 'K', 'Л': 'L',
           'М': 'M', ' Н': 'N', 'О': 'O', 'П': 'P', 'Р': 'R', 'С': 'S', 'Т': 'T', 'У': 'U',
           'Ф': 'F', 'X': 'KH', 'Ц': 'TS', 'Ч': 'CH',
           'Ш': 'SH', 'Щ': 'SCH', 'Ъ': '', 'Ы': 'Y', 'Ь': '', 'Э': 'E', 'Ю': 'YU', 'Я': 'YA', ' ': '_'}
    slug = ''
    for el in title:
        slug += dct.get(el.upper(), el)
    return slug


class Task(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    date_time_start = models.DateTimeField(auto_now_add=True)
    date_finish = models.DateField(blank=True, null=True)
    time_finish = models.TimeField(blank=True, null=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, default='Общая')
    slug = models.SlugField(blank=True)
    executor = models.ForeignKey(User, on_delete=models.CASCADE)
    priority = models.ForeignKey('Priority', on_delete=models.CASCADE, default='Normal')
    reminder = models.DateTimeField(blank=True, null=True)

    performed = 'PE'
    complete = 'CO'
    choice = [
        (performed, 'Выполняется'),
        (complete, 'Выполнено'),
    ]
    status = models.CharField(max_length=11, choices=choice, default=performed)

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

    def __str__(self):
        return f'{self.executor}: {self.title} - {self.date_finish} - {self.time_finish} - {self.status}'

    def save(self, *args, **kwargs):
        self.slug = slug_name(self.title)
        super().save(*args, **kwargs)


class SubTask(models.Model):
    id_task = models.ForeignKey('Task', on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    date_time_start = models.DateTimeField(auto_now_add=True)
    date_finish = models.DateField(blank=True, null=True)
    time_finish = models.TimeField(blank=True, null=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    slug = models.SlugField(blank=True)
    executor = models.ForeignKey(User, on_delete=models.CASCADE)
    priority = models.ForeignKey('Priority', on_delete=models.CASCADE, default='Normal')
    reminder = models.DateTimeField(blank=True, null=True)
    # control = models.ForeignKey('Control', on_delete=models.CASCADE)
    performed = 'PE'
    complete = 'CO'
    choice = [
        (performed, 'Выполняется'),
        (complete, 'Выполнено'),
    ]
    status = models.CharField(max_length=11, choices=choice, default=performed)

    class Meta:
        verbose_name = 'Подзадача'
        verbose_name_plural = 'Подзадачи'

    def __str__(self):
        return f'{self.executor}: {self.title}'

    def save(self, *args, **kwargs):
        self.slug = slug_name(self.title)
        super().save(*args, **kwargs)


class Category(models.Model):
    name = models.CharField(max_length=64)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return f'{self.name}'


class Priority(models.Model):
    low = 'Low'
    normal = 'Normal'
    high = 'Hign'
    PRIORITY = (
        (low, 'Low'),
        (normal, 'Normal'),
        (high, 'High'),
    )
    name = models.CharField(max_length=6, choices=PRIORITY, default=normal,  unique=True)

    class Meta:
        verbose_name = 'Приоритет'
        verbose_name_plural = 'Приоритеты'

    def __str__(self):
        return f'{self.name}'


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id_task = models.ForeignKey('Task', on_delete=models.CASCADE)
    date_time = models.DateTimeField(auto_now_add=True)
    text = models.TextField()

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return f'{self.id_task}: {self.text}'


class Control(models.Model):
    task = models.ForeignKey('Task', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    control = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Контроль'
        verbose_name_plural = 'Контроль'

    def __str__(self):
        return f'{self.user}-{self.control}'

app/templates/complete.html
{% extends 'index.html' %}


{% block content %}
    {% if complete|length %}
        {% for t in complete %}
            <div class="accordion" id="accordion_complete">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="heading{{ t.id }}">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ t.id }}" aria-expanded="true" aria-controls="collapse{{ t.id }}">
                            Приоритет: {{ t.priority }} - {{ t.category }} - {{ t.title }}
                        </button>
                    </h2>
                    <div id="collapse{{ t.id }}" class="accordion-collapse collapse" aria-labelledby="heading{{ t.id }}" data-bs-parent="#accordion_complete">
                        <div class="accordion-body">
                            <div class="row-cols-1">
                                Описание: {{ t.text }}
                            </div>
                            <div class="row-cols-1">
                                Задача выполнена: {{ t.date_finish|date:'d.m.Y' }}  {{ t.time_finish|time:'H:i' }}
                            </div>
                            <div class="row mb-2">
                                <div class="col-2">
                                    <strong>Подзадачи</strong>
                                </div>
                            </div>
                            {% for st in t.subtask_set.all %}
                                <div class="row mb-2">
                                    <div class="col-1">

                                    </div>
                                    <div class="col-3">
                                        {{ st.date_finish|date:'d.m.Y' }} {{ st.time_finish|time:'H:i' }}
                                    </div>
                                    <div class="col-4">
                                        {{ st.title }} - {{ st.text }} - {{ st.get_status_display }}
                                    </div>
                                    {% if st.status == 'PE' %}
                                        <div class="col-4 text-end">
                                            <a class="btn btn-sm btn-secondary" href="{% url 'subtask_complete' st.id %}" role="button">Complete</a>
                                            <a class="btn btn-sm btn-secondary" href="{% url 'subtask_update' st.id %}" role="button">Edit</a>
                                            <a class="btn btn-sm btn-secondary" href="{% url 'subtask_delete' st.id %}" role="button">Delete</a>
                                        </div>
                                    {% endif %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endblock content %}

app/templates/notes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

app/templates/task_delete.html
{% extends 'index.html' %}
<!--<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>-->
{% block content %}
<h3>Вы действительно хотите удалить задачу {{ task.title }}?</h3>
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm">
</form>
{% endblock content %}

<!--</body>
</html>-->

app/templates/task_detail.html
{% extends 'template.html' %}

{% block title %}
{% endblock title %}


{% block content %}
<p>title {{ task.title }}</p>
<p>text: {{ task.text }}</p>
<p>date_time_start: {{ task.date_time_start }}</p>
<p>date_time_finish: {{ task.date_time_finish }}</p>
<p>category: {{ task.category }}</p>
<p>slug: {{ task.slug }}</p>
<p>executor: {{ task.executor }}</p>
<p>priority: {{ task.priority }}</p>
<p>reminder: {{ task.reminder }}</p>
<p>control: {{ task.status }}</p>

{% endblock content %}

app/templates/task_edit.html
{% extends 'index.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <table>
        <tr>
            <td>{{ form }}</td>
        </tr>
    </table>
    <input type="submit" value="Save">
</form>
{% endblock content %}

app/templates/task_list.html
{% extends 'index.html' %}

{% block title %}To-Do{% endblock title %}

<!--{% block navigation %}
    <li class="nav-item"><a class="nav-link" href="{% url 'task_create' %}">New Task</a></li>
{% endblock navigation %}-->


{% block content %}
    {% load custom_filters %}
    {% if perform_today|length %}
        {% for t in perform_today %}
            <div class="accordion mb-2" id="accordion_perform_today">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="heading{{ t.id }}">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ t.id }}" aria-expanded="true" aria-controls="collapse{{ t.id }}">
                            Приоритет: {{ t.priority }} - {{ t.title }} - {{ t.category }}
                        </button>
                        <div class="progress">
                            <div class="progress-bar bg-secondary" role="progressbar" style="width: {{ t|complete_to }}%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">{{ t|complete_to }}%</div>
                        </div>
                    </h2>
                    <div id="collapse{{ t.id }}" class="accordion-collapse collapse" aria-labelledby="heading{{ t.id }}" data-bs-parent="#accordion_perform_today">
                        <div class="accordion-body">
                        <div class="row">
                                <div class="col">
                                    Срок: {{ t.date_finish|date:'d.m.Y' }}  {{ t.time_finish|time:'H:i' }}
                                </div>
                                <div class="col col-md-auto">
                                    <a class="btn btn-sm btn-secondary" href="{% url 'complete' t.id %}" role="button">Complete</a>
                                    <a class="btn btn-sm btn-secondary" href="{% url 'task_edit' t.id %}" role="button">Edit</a>
                                    <a class="btn btn-sm btn-secondary" href="{% url 'task_delete' t.id %}" role="button">Delete</a>
                                </div>
                            </div>
                            <hr>
                            <div class="row-cols-1">
                                Описание: {{ t.text }}
                            </div>
                            <hr>
                            <div class="row mb-2">
                                <div class="col-2">
                                    <strong>Подзадачи</strong>
                                </div>
                                <div class="col-1">
                                    <a class="btn btn-sm btn-secondary" href="{% url 'subtask_create' t.id %}" role="button">+</a>
                                </div>
                            </div>
                            {% for st in t.subtask_set.all %}
                                <div class="row mb-2">
                                    <div class="col-1">

                                    </div>
                                    <div class="col-3">
                                        {{ st.date_finish|date:'d.m.Y' }} {{ st.time_finish|time:'H:i' }}
                                    </div>
                                    <div class="col-4">
                                        {{ st.title }} - {{ st.text }} - {{ st.get_status_display }}
                                    </div>
                                    {% if st.status == 'PE' %}
                                        <div class="col-4 text-end">
                                            <a class="btn btn-sm btn-secondary" href="{% url 'subtask_complete' st.id %}" role="button">Complete</a>
                                            <a class="btn btn-sm btn-secondary" href="{% url 'subtask_update' st.id %}" role="button">Edit</a>
                                            <a class="btn btn-sm btn-secondary" href="{% url 'subtask_delete' st.id %}" role="button">Delete</a>
                                        </div>
                                    {% endif %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endblock content %}

app/templates/task_today_list.html
{% extends 'index.html' %}

{% block title %}To-Do{% endblock title %}


{% block content %}
    {% load custom_filters %}
    {% if perform_today_list|length %}
        {% for t in perform_today_list %}
            <div class="accordion mb-2" id="accordion_perform_today">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="heading{{ t.id }}">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ t.id }}" aria-expanded="true" aria-controls="collapse{{ t.id }}">
                            Приоритет: {{ t.priority }} - {{ t.title }} - {{ t.category }}
                        </button>
                        <div class="progress">
                            <div class="progress-bar bg-secondary" role="progressbar" style="width: {{ t|complete_to }}%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">{{ t|complete_to }}%</div>
                        </div>
                    </h2>
                    <div id="collapse{{ t.id }}" class="accordion-collapse collapse" aria-labelledby="heading{{ t.id }}" data-bs-parent="#accordion_perform_today">
                        <div class="accordion-body">
                        <div class="row">
                                <div class="col">
                                    Срок: {{ t.date_finish|date:'d.m.Y' }}  {{ t.time_finish|time:'H:i' }}
                                </div>
                                <div class="col col-md-auto">
                                    <a class="btn btn-sm btn-secondary" href="{% url 'complete' t.id %}" role="button">Complete</a>
                                    <a class="btn btn-sm btn-secondary" href="{% url 'task_edit' t.id %}" role="button">Edit</a>
                                    <a class="btn btn-sm btn-secondary" href="{% url 'task_delete' t.id %}" role="button">Delete</a>
                                </div>
                            </div>
                            <hr>
                            <div class="row-cols-1">
                                Описание: {{ t.text }}
                            </div>
                            <hr>
                            <div class="row mb-2">
                                <div class="col-2">
                                    <strong>Подзадачи</strong>
                                </div>
                                <div class="col-1">
                                    <a class="btn btn-sm btn-secondary" href="{% url 'subtask_create' t.id %}" role="button">+</a>
                                </div>
                            </div>
                            {% for st in t.subtask_set.all %}
                                <div class="row mb-2">
                                    <div class="col-1">

                                    </div>
                                    <div class="col-3">
                                        {{ st.date_finish|date:'d.m.Y' }} {{ st.time_finish|time:'H:i' }}
                                    </div>
                                    <div class="col-4">
                                        {{ st.title }} - {{ st.text }} - {{ st.get_status_display }}
                                    </div>
                                    {% if st.status == 'PE' %}
                                        <div class="col-4 text-end">
                                            <a class="btn btn-sm btn-secondary" href="{% url 'subtask_complete' st.id %}" role="button">Complete</a>
                                            <a class="btn btn-sm btn-secondary" href="{% url 'subtask_update' st.id %}" role="button">Edit</a>
                                            <a class="btn btn-sm btn-secondary" href="{% url 'subtask_delete' st.id %}" role="button">Delete</a>
                                        </div>
                                    {% endif %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endblock content %}

app/templates/task_tomorrow_list.html
{% extends 'index.html' %}

{% block title %}To-Do{% endblock title %}


{% block content %}
    {% load custom_filters %}
    {% if perform_tomorrow_list|length %}
        {% for t in perform_tomorrow_list %}
            <div class="accordion mb-2" id="accordion_perform_today">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="heading{{ t.id }}">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ t.id }}" aria-expanded="true" aria-controls="collapse{{ t.id }}">
                            Приоритет: {{ t.priority }} - {{ t.title }} - {{ t.category }}
                        </button>
                        <div class="progress">
                            <div class="progress-bar bg-secondary" role="progressbar" style="width: {{ t|complete_to }}%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">{{ t|complete_to }}%</div>
                        </div>
                    </h2>
                    <div id="collapse{{ t.id }}" class="accordion-collapse collapse" aria-labelledby="heading{{ t.id }}" data-bs-parent="#accordion_perform_today">
                        <div class="accordion-body">
                            <div class="row">
                                <div class="col">
                                    Срок: {{ t.date_finish|date:'d.m.Y' }}  {{ t.time_finish|time:'H:i' }}
                                </div>
                                <div class="col col-md-auto">
                                    <a class="btn btn-sm btn-secondary" href="{% url 'complete' t.id %}" role="button">Complete</a>
                                    <a class="btn btn-sm btn-secondary" href="{% url 'task_edit' t.id %}" role="button">Edit</a>
                                    <a class="btn btn-sm btn-secondary" href="{% url 'task_delete' t.id %}" role="button">Delete</a>
                                </div>
                            </div>
                            <hr>
                            <div class="row-cols-1">
                                Описание: {{ t.text }}
                            </div>
                            <hr>
                            <div class="row mb-2">
                                <div class="col-2">
                                    <strong>Подзадачи</strong>
                                </div>
                                <div class="col-1">
                                    <a class="btn btn-sm btn-secondary" href="{% url 'subtask_create' t.id %}" role="button">+</a>
                                </div>
                            </div>
                            {% for st in t.subtask_set.all %}
                                <div class="row mb-2">
                                    <div class="col-1">

                                    </div>
                                    <div class="col-3">
                                        {{ st.date_finish|date:'d.m.Y' }} {{ st.time_finish|time:'H:i' }}
                                    </div>
                                    <div class="col-4">
                                        {{ st.title }} - {{ st.text }} - {{ st.get_status_display }}
                                    </div>
                                    {% if st.status == 'PE' %}
                                        <div class="col-4 text-end">
                                            <a class="btn btn-sm btn-secondary" href="{% url 'subtask_complete' st.id %}" role="button">Complete</a>
                                            <a class="btn btn-sm btn-secondary" href="{% url 'subtask_update' st.id %}" role="button">Edit</a>
                                            <a class="btn btn-sm btn-secondary" href="{% url 'subtask_delete' st.id %}" role="button">Delete</a>
                                        </div>
                                    {% endif %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endblock content %}

app/templates/task_yesterday_list.html
{% extends 'index.html' %}

{% block title %}To-Do{% endblock title %}


{% block content %}
    {% load custom_filters %}
    {% if perform_yesterday_list|length %}
        {% for t in perform_yesterday_list %}
            <div class="accordion mb-2" id="accordion_perform_today">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="heading{{ t.id }}">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ t.id }}" aria-expanded="true" aria-controls="collapse{{ t.id }}">
                            Приоритет: {{ t.priority }} - {{ t.title }} - {{ t.category }}
                        </button>
                        <div class="progress">
                            <div class="progress-bar bg-secondary" role="progressbar" style="width: {{ t|complete_to }}%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">{{ t|complete_to }}%</div>
                        </div>
                    </h2>
                    <div id="collapse{{ t.id }}" class="accordion-collapse collapse" aria-labelledby="heading{{ t.id }}" data-bs-parent="#accordion_perform_today">
                        <div class="accordion-body">
                            <div class="row">
                                <div class="col">
                                    Срок: {{ t.date_finish|date:'d.m.Y' }}  {{ t.time_finish|time:'H:i' }}
                                </div>
                                <div class="col col-md-auto">
                                    <a class="btn btn-secondary btn-sm" href="{% url 'complete' t.id %}" role="button">Complete</a>
                                    <a class="btn btn-secondary btn-sm" href="{% url 'task_edit' t.id %}" role="button">Edit</a>
                                    <a class="btn btn-secondary btn-sm" href="{% url 'task_delete' t.id %}" role="button">Delete</a>
                                </div>
                            </div>
                            <hr>
                            <div class="row-cols-1">
                                Описание: {{ t.text }}
                            </div>
                            <hr>
                            <div class="row mb-2">
                                <div class="col-2">
                                    <strong>Подзадачи</strong>
                                </div>
                                <div class="col-1">
                                    <a class=" btn btn-sm btn-secondary" href="{% url 'subtask_create' t.id %}" role="button">+</a>
                                </div>
                            </div>
                            {% for st in t.subtask_set.all %}
                                <div class="row mb-2">
                                    <div class="col-1">

                                    </div>
                                    <div class="col-3">
                                        {{ st.date_finish|date:'d.m.Y' }} {{ st.time_finish|time:'H:i' }}
                                    </div>
                                    <div class="col-4">
                                        {{ st.title }} - {{ st.text }} - {{ st.get_status_display }}
                                    </div>
                                    {% if st.status == 'PE' %}
                                        <div class="col-4 text-end">
                                            <a class="btn btn-sm btn-secondary" href="{% url 'subtask_complete' st.id %}" role="button">Complete</a>
                                            <a class="btn btn-sm btn-secondary" href="{% url 'subtask_update' st.id %}" role="button">Edit</a>
                                            <a class="btn btn-sm btn-secondary" href="{% url 'subtask_delete' st.id %}" role="button">Delete</a>
                                        </div>
                                    {% endif %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endblock content %}

app/templates/template.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock title %}</title>
        {% load static %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" href="#">
                    <img src="{% static 'images/ToDo from Alex.png'%}" alt="Logo"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">

                        {% block navigation %}

                        {% endblock navigation %}
                            <li class="nav-item"><a class="nav-link" href="/admin/">Admin</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'profile' request.user.id %}">User: {{ request.user.username }}</a><a href="/accounts/logout/">Logout<a/></li>
                        {% else %}
                            <li class="nav-item"><a class="nav-link" href="">Вы вошли как Гость</a><a href="/accounts/login/">Login<a/></li></li>
                        {% endif %}

                        <!--<li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>-->
                    </ul>
                </div>
            </div>
        </nav>

        <header class="bg-primary bg-gradient text-white">
            <div class="container px-4 text-center">
                <h1 class="fw-bolder">ToDo</h1>
                <p class="lead">ToDo</p>
                <!--<a class="btn btn-lg btn-light" href="#about">Start scrolling!</a>-->
            </div>
        </header>

        <!-- Page content-->
        <div class="container px-4">
            <div class="row gx-4 justify-content-center">
                    <div class="col-lg-8">

            {% block content %}
            {% endblock content %}
                    </div>
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

app/templates/today.html
{% extends 'index.html' %}


{% block content %}



{% endblock content %}